### ISSUE TITLE
About token embedding in NEXUS

### ISSUE THREAD

**Issue by pyz-creeper** [Kevin-Zh-CS/NEXUS#5]
Hi,
Thanks for the excellent paper and code! I have a question regarding the implementation of token embedding in NEXUS. I wasn't able to find any specific details on this and couldn't locate a direct implementation of that functionality in this codebase. While I understand that token embedding can be viewed as a special form of matrix multiplication, it doesn't seem to be explicitly mentioned in TABLE 4. Could you clarify how token embedding is implemented in NEXUS?

**Comment by Drey563** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by pyz-creeper** [comment]
Hi dear developers, I can not see your reply or open the link in your previous comment which was automatically sent via email.
